name: shopping_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.0

dependencies:
  animated_bottom_navigation_bar: ^1.3.3
  flutter:
    sdk: flutter
  flutter_animate: ^4.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Matemasie
      fonts:
        - asset: assets/fonts/Matemasie-Regular.ttf
